export type CatalogCourse = {
  legacyCode?: string;
  code: string;
  name: string;
  description: string;
  term: "UoA · Stage I" | "UoA · Stage II" | "UoA · Stage III";
  accent: string;
  icon: string;
  progress: number;
};

/**
 * University of Auckland undergraduate COMPSCI courses in the 2026 BSc
 * schedule. Legacy codes are retained only to upgrade the original three
 * demonstration courses without breaking their materials or conversations.
 */
export const uoaUndergraduateCourses: readonly CatalogCourse[] = [
  {
    legacyCode: "COMP101",
    code: "COMPSCI 101",
    name: "Principles of Programming",
    description: "Learn programming in Python through variables, control structures, functions, lists, dictionaries, and standard modules.",
    term: "UoA · Stage I",
    accent: "#6d5dfc",
    icon: "terminal-square",
    progress: 68,
  },
  {
    code: "COMPSCI 110",
    name: "Introduction to Computer Systems",
    description: "Explore how computer systems represent data and combine hardware, operating systems, networks, and security.",
    term: "UoA · Stage I",
    accent: "#4f7df3",
    icon: "cpu",
    progress: 0,
  },
  {
    code: "COMPSCI 111",
    name: "An Introduction to Practical Computing",
    description: "Develop practical computing skills and an informed understanding of the digital tools used in study, work, and society.",
    term: "UoA · Stage I",
    accent: "#9b63d9",
    icon: "monitor-cog",
    progress: 0,
  },
  {
    code: "COMPSCI 120",
    name: "Mathematics for Computer Science",
    description: "Build mathematical foundations for computer science through logic, sets, functions, counting, probability, and graphs.",
    term: "UoA · Stage I",
    accent: "#7658c9",
    icon: "sigma",
    progress: 0,
  },
  {
    code: "COMPSCI 130",
    name: "Introduction to Software Fundamentals",
    description: "Develop reliable software using object-oriented programming, recursion, common data structures, and algorithmic problem solving.",
    term: "UoA · Stage I",
    accent: "#5869cf",
    icon: "code-2",
    progress: 0,
  },
  {
    code: "COMPSCI 210",
    name: "Computer Organisation",
    description: "Study low-level programming and the organisation of processors, memory, input/output, and computer instruction execution.",
    term: "UoA · Stage II",
    accent: "#1682b8",
    icon: "cpu",
    progress: 0,
  },
  {
    code: "COMPSCI 215",
    name: "Data Communications and Security",
    description: "Learn how data moves through computer networks and examine protocols, internet architecture, cryptography, and security fundamentals.",
    term: "UoA · Stage II",
    accent: "#158b9b",
    icon: "shield-check",
    progress: 0,
  },
  {
    legacyCode: "COMP201",
    code: "COMPSCI 220",
    name: "Algorithms and Data Structures",
    description: "Analyse algorithms and data structures using asymptotic complexity, sorting, searching, graph traversal, and graph optimisation.",
    term: "UoA · Stage II",
    accent: "#0d9f8f",
    icon: "network",
    progress: 43,
  },
  {
    code: "COMPSCI 225",
    name: "Discrete Structures in Mathematics and Computer Science",
    description: "Study logic, counting, induction, recursion, sets and functions, graphs, codes, and finite automata.",
    term: "UoA · Stage II",
    accent: "#3b86a6",
    icon: "sigma",
    progress: 0,
  },
  {
    code: "COMPSCI 230",
    name: "Object Oriented Software Development",
    description: "Design and implement object-oriented software using abstraction, reusable components, design principles, and testing.",
    term: "UoA · Stage II",
    accent: "#238c7a",
    icon: "code-2",
    progress: 0,
  },
  {
    code: "COMPSCI 235",
    name: "Software Development Methodologies",
    description: "Apply modern software processes, requirements analysis, teamwork, version control, testing, and agile development practices.",
    term: "UoA · Stage II",
    accent: "#397c73",
    icon: "workflow",
    progress: 0,
  },
  {
    code: "COMPSCI 289",
    name: "Research Seminar in Computer Science",
    description: "Discover computer science research areas while developing skills in reading, discussing, and communicating research.",
    term: "UoA · Stage II",
    accent: "#5676a8",
    icon: "search",
    progress: 0,
  },
  {
    code: "COMPSCI 290",
    name: "Special Topic",
    description: "Study a selected contemporary topic in computer science offered for the current academic period.",
    term: "UoA · Stage II",
    accent: "#61718f",
    icon: "book-open",
    progress: 0,
  },
  {
    code: "COMPSCI 313",
    name: "Computer Architecture",
    description: "Examine modern computer architecture, including processors, instruction pipelines, memory hierarchies, and parallel systems.",
    term: "UoA · Stage III",
    accent: "#d66a3d",
    icon: "cpu",
    progress: 0,
  },
  {
    code: "COMPSCI 315",
    name: "Data Communications Technologies",
    description: "Study network technologies and protocols, routing, congestion control, wireless communication, and internet performance.",
    term: "UoA · Stage III",
    accent: "#c66b45",
    icon: "network",
    progress: 0,
  },
  {
    code: "COMPSCI 316",
    name: "Cyber Security",
    description: "Analyse security threats and defences across cryptography, authentication, access control, networks, and software systems.",
    term: "UoA · Stage III",
    accent: "#c75a55",
    icon: "shield-check",
    progress: 0,
  },
  {
    code: "COMPSCI 320",
    name: "Applied Algorithmics",
    description: "Design provably correct and efficient algorithms and explore complexity, NP-completeness, approximation, and randomisation.",
    term: "UoA · Stage III",
    accent: "#d2783f",
    icon: "network",
    progress: 0,
  },
  {
    code: "COMPSCI 331",
    name: "Large-Scale Software Development",
    description: "Build substantial software in teams using architecture, collaborative workflows, quality assurance, and continuous integration.",
    term: "UoA · Stage III",
    accent: "#b86e55",
    icon: "workflow",
    progress: 0,
  },
  {
    code: "COMPSCI 335",
    name: "Web Programming and Distributed Services",
    description: "Create modern web applications and distributed services using web protocols, APIs, data exchange, and service architecture.",
    term: "UoA · Stage III",
    accent: "#b75b72",
    icon: "globe",
    progress: 0,
  },
  {
    code: "COMPSCI 340",
    name: "Operating Systems",
    description: "Understand processes, threads, concurrency, scheduling, virtual memory, file systems, and operating-system design.",
    term: "UoA · Stage III",
    accent: "#a96c55",
    icon: "monitor-cog",
    progress: 0,
  },
  {
    code: "COMPSCI 345",
    name: "Human-computer Interaction",
    description: "Design usable interactive systems through user-centred research, prototyping, interface design, and evaluation.",
    term: "UoA · Stage III",
    accent: "#b65f85",
    icon: "users",
    progress: 0,
  },
  {
    code: "COMPSCI 350",
    name: "Mathematical Foundations of Computer Science",
    description: "Explore formal mathematical ideas that underpin computation, reasoning, languages, and theoretical computer science.",
    term: "UoA · Stage III",
    accent: "#ad647f",
    icon: "sigma",
    progress: 0,
  },
  {
    legacyCode: "COMP301",
    code: "COMPSCI 351",
    name: "Fundamentals of Database Systems",
    description: "Study relational data modelling, SQL, normalisation, query processing and optimisation, transactions, recovery, and security.",
    term: "UoA · Stage III",
    accent: "#ed8b45",
    icon: "database",
    progress: 24,
  },
  {
    code: "COMPSCI 361",
    name: "Machine Learning",
    description: "Learn core supervised and unsupervised learning methods, model evaluation, feature design, and responsible application.",
    term: "UoA · Stage III",
    accent: "#c66d6d",
    icon: "network",
    progress: 0,
  },
  {
    code: "COMPSCI 367",
    name: "Artificial Intelligence",
    description: "Study intelligent agents, search, knowledge representation, reasoning, planning, and other foundational AI techniques.",
    term: "UoA · Stage III",
    accent: "#a8669a",
    icon: "cpu",
    progress: 0,
  },
  {
    code: "COMPSCI 369",
    name: "Computational Methods in Interdisciplinary Science",
    description: "Apply computational modelling and analysis to scientific problems that cross traditional disciplinary boundaries.",
    term: "UoA · Stage III",
    accent: "#9a6aa5",
    icon: "code-2",
    progress: 0,
  },
  {
    code: "COMPSCI 373",
    name: "Computer Graphics and Image Processing",
    description: "Explore geometric modelling, rendering, image representation, transformation, enhancement, and visual computing algorithms.",
    term: "UoA · Stage III",
    accent: "#bb637f",
    icon: "image",
    progress: 0,
  },
  {
    code: "COMPSCI 380",
    name: "Project in Computer Science",
    description: "Complete an approved supervised computer science project and communicate its process, results, and significance.",
    term: "UoA · Stage III",
    accent: "#a97054",
    icon: "workflow",
    progress: 0,
  },
  {
    code: "COMPSCI 380A",
    name: "Project in Computer Science",
    description: "Begin the first 7.5-point component of an approved supervised computer science project spanning two enrolments.",
    term: "UoA · Stage III",
    accent: "#9f735a",
    icon: "workflow",
    progress: 0,
  },
  {
    code: "COMPSCI 380B",
    name: "Project in Computer Science",
    description: "Complete the second 7.5-point component of an approved supervised computer science project spanning two enrolments.",
    term: "UoA · Stage III",
    accent: "#947660",
    icon: "workflow",
    progress: 0,
  },
  {
    code: "COMPSCI 389",
    name: "Research Methods in Computer Science",
    description: "Develop research questions, review literature, select methods, address ethics, and communicate a research proposal.",
    term: "UoA · Stage III",
    accent: "#9c6c83",
    icon: "search",
    progress: 0,
  },
  ...["390", "391", "392", "393"].map((number, index): CatalogCourse => ({
    code: `COMPSCI ${number}`,
    name: "Special Topic",
    description: "Study a selected advanced or emerging topic in computer science offered for the current academic period.",
    term: "UoA · Stage III",
    accent: ["#966b91", "#8c6d9b", "#826fa5", "#7871af"][index],
    icon: "book-open",
    progress: 0,
  })),
  {
    code: "COMPSCI 399",
    name: "Capstone: Computer Science",
    description: "Work in a team to take a substantial computer science project from conception through production and presentation.",
    term: "UoA · Stage III",
    accent: "#6f70b8",
    icon: "graduation-cap",
    progress: 0,
  },
];
